### ISSUE TITLE
ModuleNotFoundError: No module named 'fastLlama' after setup.py update

### ISSUE THREAD

**Issue by yevhen-kalyna** [PotatoSpudowski/fastLLaMa#32] opened 2023-03-30 13:54 UTC
```
$ python example-alpaca.py
Traceback (most recent call last):
  File "/home/yevhen/Documents/Projects/fastLLaMa/example-alpaca.py", line 5, in <module>
    import fastLlama
ModuleNotFoundError: No module named 'fastLlama'
```

In `example-alpaca.py` I changed only `sys.path` (to full path), `model path` and `model id`.

How I build it:
```
▶python setup.py                                                                                       
An error occurred while running 'make': Command '['cd ./build && cmake .. && make']' returned non-zero exit status 2.
Output: -- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test NATIVE_C_FLAG_SUPPORTED
-- Performing Test NATIVE_C_FLAG_SUPPORTED - Success
-- Performing Test C_FLAG_SUPPORTED_mavx2
-- Performing Test C_FLAG_SUPPORTED_mavx2 - Success
-- Performing Test C_FLAG_SUPPORTED_mf16c
-- Performing Test C_FLAG_SUPPORTED_mf16c - Success
-- Performing Test C_FLAG_SUPPORTED_march=native
-- Performing Test C_FLAG_SUPPORTED_march=native - Success
-- Performing Test C_FLAG_SUPPORTED_mfma
-- Performing Test C_FLAG_SUPPORTED_mfma - Success
-- Performing Test C_FLAG_SUPPORTED_mavx
-- Performing Test C_FLAG_SUPPORTED_mavx - Success
-- Performing Test C_FLAG_SUPPORTED_AVX
-- Performing Test C_FLAG_SUPPORTED_AVX - Failed
-- Performing Test C_FLAG_SUPPORTED_SSE2
-- Performing Test C_FLAG_SUPPORTED_SSE2 - Failed
-- Performing Test C_FLAG_SUPPORTED_AVX2
-- Performing Test C_FLAG_SUPPORTED_AVX2 - Failed
-- Performing Test C_FLAG_SUPPORTED_GL
-- Performing Test C_FLAG_SUPPORTED_GL - Failed
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- pybind11 v2.10.4 
-- Found PythonInterp: /home/yevhen/.cache/pypoetry/virtualenvs/fastLLaMa-bxKZnhHe-py3.10/bin/python (found suitable version "3.10.9", minimum required is "3.6") 
-- Found PythonLibs: /home/yevhen/.pyenv/versions/3.10.9/lib/libpython3.10.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done (4.5s)
-- Generating done (0.0s)
-- Build files have been written to: /home/yevhen/Documents/Projects/fastLLaMa/build
[ 20%] Building C object CMakeFiles/fast_llama_lib.dir/ggml.c.o
[ 40%] Building CXX object CMakeFiles/fast_llama_lib.dir/utils.cpp.o
[ 60%] Linking CXX static library libfast_llama_lib.a
[ 60%] Built target fast_llama_lib
[ 80%] Building CXX object CMakeFiles/fastLlama.dir/bridge.cpp.o
[100%] Linking CXX shared module fastLlama.so

▶tree build | grep fastLlama.so
<EMPTY_RESULT>

▶python example-alpaca.py
Traceback (most recent call last):
  File "/home/yevhen/Documents/Projects/fastLLaMa/example-alpaca.py", line 5, in <module>
    import fastLlama
ModuleNotFoundError: No module named 'fastLlama'
```

Manual building (when the automatic build is already done):
```
▶cd ./build && cmake .. && make
-- Performing Test C_FLAG_SUPPORTED_march=native
-- Performing Test C_FLAG_SUPPORTED_march=native - Success
-- pybind11 v2.10.4 
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/yevhen/Documents/Projects/fastLLaMa/build
[ 60%] Built target fast_llama_lib
[ 80%] Linking CXX shared module fastLlama.so
/usr/bin/ld: libfast_llama_lib.a(ggml.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fastLlama.dir/build.make:98: fastLlama.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:128: CMakeFiles/fastLlama.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

▶cmake ..
-- Performing Test C_FLAG_SUPPORTED_march=native
-- Performing Test C_FLAG_SUPPORTED_march=native - Success
-- pybind11 v2.10.4 
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/yevhen/Documents/Projects/fastLLaMa/build

▶make
[ 60%] Built target fast_llama_lib
[ 80%] Linking CXX shared module fastLlama.so
/usr/bin/ld: libfast_llama_lib.a(ggml.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fastLlama.dir/build.make:98: fastLlama.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:128: CMakeFiles/fastLlama.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

My versions:
```
▶gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

▶g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

▶cmake --version
cmake version 3.26.1
```

**Comment by stduhpf** [comment] 2023-03-30 14:50
Have you tried removing all build outputs ( for example using `git clean -f -d -X`) and trying to build again?

**Comment by stduhpf** [comment] 2023-03-30 16:32
I can confirm it's broken for me too, I should have tried to reproduce your issue before asking stupid questions.

**Comment by yevhen-kalyna** [comment] 2023-03-30 17:06
@amitsingh19975 Works for me.

**Comment by stduhpf** [comment] 2023-03-30 17:18
Compilation works, but `./quantize` executable is not generated anymore?

**Comment by amitsingh19975** [comment] 2023-03-30 18:33
Yes, @PotatoSpudowski should be on it.

**Comment by amitsingh19975** [comment] 2023-03-30 18:35
We are cleaning the whole project so that we can have a more maintainable project.

**Comment by PotatoSpudowski** [comment] 2023-03-30 19:41
Please test it out and let us know :)

**Comment by stduhpf** [comment] 2023-03-30 22:10
Seems to be working

**Comment by PotatoSpudowski** [comment] 2023-03-31 06:58
Closing this for now, Please feel free to reopen if necessary :)

**Closed** 2023-04-15 21:38 UTC
